Fix ToUInt: 2^n doesn't fit n bits
Sunscreen-tech/Sunscreen pull request #323
Opened 2023-10-14 18:06 UTC by JoseSK999

Also a small change to the AssertBinary comment to reflect the actual constraint used

2023-10-24 20:11 UTC, samtay requested changes
Thanks for your contribution! Just one small change requested.

2023-10-24 20:11 UTC, samtay commented on sunscreen/src/types/zkp/gadgets/binary.rs
> +        if *val >= BigInt::ONE.shl_vartime(self.n) {
Good catch! This is actually still incorrect when `n == 512`, however, as `BigInt::ONE.shl_vartime(512) == BigInt::ZERO`. I believe the correct fix is to change this line to

```suggestion
        if *val > BigInt::ONE.shl_vartime(self.n).wrapping_sub(&BigInt::ONE) {
```

2023-10-25 09:48 UTC, JoseSK999 commented
Right @samtay, fixed

2023-10-25 20:24 UTC, samtay approved these changes

2023-10-25 20:24 UTC, merged